name: Continuous integration and deployment of the OCLettings Django application

on:
  push:
    branches:
      - master

jobs:
  test-and-lint:

    name: Test app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Pull repo
      - name: Set up Python 3.9
        uses: actions/setup-python@v4  # Configure Python
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: chartboost/ruff-action@v1
        with:
          args: --line-length=119
      - name: Lint wint flake8
        run: |
          pip install flake8
          flake8
      - name: Django testing
        run: python3 manage.py test

  deployment:

    name: Deploy app
    runs-on: ubuntu-latest
    needs: test-and-lint

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        
