name: Continuous integration of the Django application OCLettings

on:
  push:
    branches:
      - dev
      - master

jobs:
  test-and-lint:  # deploy step, naming: build and deploy

    runs-on: ubuntu-latest
    #container: karnex/oclettings:latest --> to implement for the CD step --> test container or deploy-pull

    steps:
      - uses: actions/checkout@v3  # Pull repo
      - name: Set up Python 3.9
        uses: actions/setup-python@v4  # Configure Python
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: chartboost/ruff-action@v1
        with:
          args: --line-length=119
      - name: Lint wint flake8
        run: |
          pip install flake8
          flake8
      - name: Django testing
        run: |
          python3 manage.py test
        
