name: Continuous integration of the Django application OCLettings

on:
  push:
    branches:
      - dev
      - master

jobs:
  test-and-lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Pull repo
      - name: Set up Python 3.9
        uses: actions/setup-python@v4  # Configure Python
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8
      - name: Django testing
        run: |
          python3 manage.py test
        
